### ISSUE TITLE
noSuchFieldError: numGroup (with CofhCore 3.0.1-254)

### ISSUE THREAD

**Issue by shadoxxhd** [TheTemportalist/ThaumicExpansion#10]
http://pastebin.com/iCi5kYrf

**Comment by shadoxxhd** [comment]
anyone have an idea how to fix this?

**Comment by wooby6** [comment]
Duplicate #6

**Comment by shadoxxhd** [comment]
will you fix this, or move straight on to the new implementation? i liked
the old design more :/

**Comment by TheTemportalist** [comment]
The new system is already in place and released. It is not too much different then the previous version except that you need to run RF power through the converter block in order to utilize it.
