### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by rcistano** [TheTemportalist/ThaumicExpansion#16]
the Analyzer looks nothing like the picture(s) in the Wiki as well as the logo icon. The Analyzer that is in the mod will not work as it wont accept RF , has no upgrade slots or anything.

**Comment by TheTemportalist** [comment]
This wiki is old. This is not a bug or problem. You can place the apparatus on the analyzer and feed the apparatus RF and the analyzer will be powered.

**Comment by rcistano** [comment]
This still cannot be powered.
