### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by rcistano** [TheTemportalist/ThaumicExpansion#17]
Game crashes when Analyzer is placed down.

**Comment by wooby6** [comment]
logs or it didn't happen

**Comment by rcistano** [comment]
Solution: Get rid of Mod.

Perfect idea!

**Comment by TheTemportalist** [comment]
Crash logs are required.

**Comment by rcistano** [comment]
I have less frustration without the mod than I do with the mod.

**Comment by TheTemportalist** [comment]
Should be fixed in latest curseforge release. http://minecraft.curseforge.com/projects/thaumic-expansion/files/2265777
