### ISSUE TITLE
Crash when placing

### ISSUE THREAD

**Issue by Puremin0rez** [TheTemportalist/ThaumicExpansion#18]
http://pastebin.com/523SfjAZ

Also the analyzer(s) have no recipes

**Comment by TheTemportalist** [comment]
Yeah, I'm aware. Working on this and a few other features. I'll leave this open until I can push a release.

**Comment by Puremin0rez** [comment]
Thanks, just letting you know :) looking forward too it.

**Comment by TheTemportalist** [comment]
Should be fixed in latest curseforge release. http://minecraft.curseforge.com/projects/thaumic-expansion/files/2265777
