### ISSUE TITLE
Missing mods exception?

### ISSUE THREAD

**Issue by Wolfseverest93** [TheTemportalist/ThaumicExpansion#19]
This is a bit of an eyebrow raiser for me since your mod doesn't tell me what it's missing, and also the forum and curse locations don't say what it requires, so I'm assuming it simply requires at least thaumcraft and thermal expansion based on the name of the mod and what it's said to do.

I verified it being this mod by removing it from the pack and successfully relaunching without a single error.

Missing Mods:
    origin : [5,)

cpw.mods.fml.common.MissingModsException
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:243)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
    at java.lang.Thread.run(Thread.java:745)

**Comment by wooby6** [comment]
Thermal Expansion - not required anymore
Thaumcraft 4 - yes 
 what your missing is the origin api http://minecraft.curseforge.com/projects/origin/files

**Comment by Wolfseverest93** [comment]
Could you list that as a prerequisite in the curse and minecraftforum please? I'm surprised I didn't notice that was what it was talking about. Now I feel like I need sleep. Thank you for the swift reply!

**Comment by Drullkus** [comment]
[Thaumic Expansion](http://minecraft.curseforge.com/projects/thaumic-expansion/files/2264346) requires Origin. Not Chisel.

**Comment by TheTemportalist** [comment]
Each file uploaded to CurseForge has Origin labeled as a required library, but I will add a note in the description to make it more explicit.

**Comment by Drullkus** [comment]
> Thaumic Expansion requires Origin. Not Chisel.

Crap. Didn't realize I was commenting on the Thaumic-Ex issue tracker, not Chisel's. My apologies, @TheTemportalist. xD
