### ISSUE TITLE
Memeory Leak

### ISSUE THREAD

**Issue by AhmiDarrow** [TheTemportalist/ThaumicExpansion#20]
Well first of all let me say that we LOVE this mod! Needs a little balancing but that's not what I'm here to say :P 

That being said once we started using it we encountered an issue where Minecraft started to eat memory until there was none left. The issue seems to stem from interaction with inventory tweaks and iron chests somehow. I'm at work at the moment and cannot supply a log for you which I will do once I get home tonight as it may not just be this mod as we run a custom modpack with 253 mods including this one. But we have yet to have any issues until we actually built and started using the analyzer. I'll send some detailed logs when I get home. 

P.S. Love the mod and would love to help in any way.

**Comment by TheTemportalist** [comment]
Wonderful. Thanks for the heads up. Hopefully I can take care of the issue this weekend.

**Comment by AhmiDarrow** [comment]
Sorry it took me so long to get this up, it's to big for pastebin so i put it on my dropbox:
https://www.dropbox.com/s/g5m75tn5vuoyxym/fml-client-latest.log?dl=0

If you skip all the way to the bottom, that will spam until you freeze and have to end minecraft from the task manager. It seems like it takes about 2 hours of play before this happens. This is a client side only issue as the server is seemingly unaffected while this happens. Again i'm not sure if it's thaumic expansion, inventory tweaks or iron chests but we only started to have this issue once we actually started using the analyzer. If we don't use it at all it doesn't seem to happen either. So it's something with the gui is my best guess.

**Comment by TheTemportalist** [comment]
Between timestamps 11:08:03 and 11:52:22, it is all output from inventorytweaks, so I am thinking it is how they are interacting with the gui. Cannot be sure though.

**Comment by AhmiDarrow** [comment]
Any suggestions?

**Comment by TheTemportalist** [comment]
I have some thoughts, and some test code. If you would be willing to test, we can get some testing running.

**Comment by AhmiDarrow** [comment]
Yes I'd be more then happy to help out!

**Comment by TheTemportalist** [comment]
Try testing this build with the latest Origin on curseforge, see if it does anything. https://jenkins.dries007.net/view/Temportal/job/ThaumicExpansion/36/

**Comment by TheTemportalist** [comment]
Have you brought this up with the team for inventorytweaks yet? I would be interested in their input.

**Comment by AhmiDarrow** [comment]
I have them and am installing. I will run it through the ringer to see if it still has issues. I posted on inventory tweaks about the issue and provided the log i'll let you know what they say once I get a response. Thanks by the way :)

**Comment by AhmiDarrow** [comment]
So they basically said "We no longer support 1.7.10, try to reproduce it in 1.8"

...

**Comment by TheTemportalist** [comment]
I just laughed for a solid 2 minutes straight... Haha
That really sucks because I'm not doing 1.8 things....

**Comment by AhmiDarrow** [comment]
Yea me either I run 253 mods and like MAYBE 15 or 20 are compatible with 1.8.

**Comment by TheTemportalist** [comment]
Well, see if you got any better performance from that build and we can work from there.

**Comment by AhmiDarrow** [comment]
Yea I have it running on the server and client now, dumping stacks of cobble to keep the machine running. So far so good, i'll let you know how it plays out though. 

And thanks again, I really appreciate it!

**Comment by TheTemportalist** [comment]
No problem! We will have to chat about your input on balancing sometime.

**Comment by AhmiDarrow** [comment]
Hey so a little early to say but I think it's fixed. It was happening consistently without fail within a few hours and the clients are holding steady at 3.8 - 4.2 gigs of ram which is what are pack runs on average. No drop is TPS or FPS that I can tell so.... THANKS! :)

**Comment by TheTemportalist** [comment]
Ha. Serves me right for leaving debug code in the renderer class...
