### ISSUE TITLE
Server crash on block placement and GUI access

### ISSUE THREAD

**Issue by bookerthegeek** [TheTemportalist/ThaumicExpansion#7]
http://pastebin.com/3DSuT5Ep
First report is when placing the machine into the world. On a side not, any/all ender IO conduit also needed to be removed to get the server to not crash when loading the chunk.

http://pastebin.com/r7uAxXXt
Second report is when accessing the GUI interface.

SO the first time we placed it on an Ender IO conduit, and crashed. We World edited it out and tried again on dirt thinking something wierd going on between you and Ender IO. Still crash, but could load up the world again without crashing. Which promptly crashed the server again when accessing the GUI.

Did not know if this is a duplication of https://github.com/TheTemportalist/ThaumicExpansion/issues/6 so I created a new post.

**Comment by wooby6** [comment]
this is a duplication of #6

**Comment by TheTemportalist** [comment]
With this being a duplicate issue, I will close this thread. In the future, please separate crashes by different issues.
